module.exports = {
  CITIZENSHIP: 'in order to attend Georgia State, you must verify your lawful presence in the U.S. Here are your options for doing so: bit.ly/gsu-verify. You can email document copies (excluding birth certificate) to lawfulpresenceua@gsu.edu or bring them in person to the admissions office.',
  EMERGENCY_CONTACT_HOLD: 'you still need to remove the emergency contact hold in PAWS before school starts. 📚  Update the info in the Enrollment tab and you’re good to go!',
  TRANSPORTATION: 'I’m not sure how you are planning to get around 🚀  but before classes begin, Georgia State needs to know: Do you plan to park a car on campus?',
  IMMUNIZATIONS: 'Immunizations 💉  are required for MMR, Tetanus/Diphtheria, Varicella, Hep B (and meningitis if you live on campus). Your doctor’s office can submit your immunization form (bit.ly/immune-form) via fax (404-413-1955) or mail (141 Piedmont Avenue, Suite D, Atlanta, GA 3030). Visit bit.ly/gsu-immunization for more info.',
  AB_IB_SCORES_REMINDER: 'AP (and IB) test scores 📝  for 2016 will be available in early July. If you’ve already opted to send your scores to Georgia State (or haven’t taken any AP exams), then you’re good to go. If you aren’t sure or you need to send an AP score report to GSU, please visit bit.ly/gsu-ap-credit and follow the instructions.',
  TRANSCRIPTS_REMINDER: 'Georgia State needs to have your final transcript 📜  on file before the first day of fall classes, so please make sure your high school mails it to our admissions office. Here’s our request form if you need one: bit.ly/gsu-transcript.',
  DOESNT_ATTEND_ORIENTATION_1: 'If you want Georgia State to consider you for financial aid, file the FAFSA and submit it to GSU. Do it ASAP so you can get funds in time for fall semester.',
  DOESNT_ATTEND_ORIENTATION_2: 'You still need to submit verification documents before Georgia State can offer you financial aid. Check PAWS to see what you’re missing and send it in ASAP.',
  DOESNT_ATTEND_ORIENTATION_3: 'You qualify for a financial aid package from Georgia State. 💰 If you haven’t claimed your award yet, visit bit.ly/accept-aid for instructions',
  EMERGENCY_CONTACT_HOLD_REMINDER: 'You still need to remove the emergency contact hold in PAWS before school starts. 📚  Update the info in the Enrollment tab and you’re good to go!',
  CITZENSHIP_LAWFUL_PRESCENSE_VERIFICATION_REMINDER: 'In order to attend Georgia State, you must verify your lawful presence in the U.S. Here are your options for doing so: bit.ly/gsu-verify. You can email document copies (excluding birth certificate) to lawfulpresenceua@gsu.edu or bring them in person to the admissions office.',
  IMMUNIZATION_REMINDER: 'Please submit your immunization  💉  form: bit.ly/immune-form. Your doctor’s office can fax it to 404-413-1955 or mail it to 141 Piedmont Avenue, Suite D, Atlanta, GA 30303. Or you can stop by the Student Health Clinic to get any required shots you may need. Visit bit.ly/gsu-immunization for more info.',
  TRANSCRIPT_REMINDER: 'Georgia State needs to have your final transcript 📜  on file before the first day of fall classes, so please make sure your high school mails it to our admissions office. Here’s our request form if you need one: bit.ly/gsu-transcript.',
  ORIENTATION_REMINDER: 'Hi! You’re scheduled to attend orientation tomorrow. Check-in begins at 7AM in the Student Recreation Center 🏫 at 101 Piedmont Avenue SE, and activities begin at 8AM. 🕖 Here’s a checklist to help you along the way: bit.ly/1O3UDMp. See you soon!'
}